apiVersion: v1
kind: Service
metadata:
  name: helloworld
  labels:
    app: hellloworld
spec:
  ports:
    - name: web
      port: 80
      targetPort: 8080
      protocol: TCP
  type: LoadBalancer
  selector:
    app: helloworld